// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cajibxvkxrgxorzywypt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhamlieHZreHJneG9yenl3eXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0OTI0MjYsImV4cCI6MjA1NzA2ODQyNn0.aDPYQF2iX4aF4PPhlR5AOZ5bc6_jHoJGARnuTQOEekU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);